.github/PULL_REQUEST_TEMPLATE.md
.github/config.yml

Signed-off-by: Drew Robinson <drew.robinson@gmail.com>
This PR fixes issue #3 
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

Attempt to correct image path in bot welcome message

---

adapter/adapter.go
adapter/k8s.go

Signed-off-by: Michael Gfeller <mgfeller@mgfeller.net>
This PR fixes #7 
Code from meshery-consul, also used in other adapters.

Add function GetServicePorts() to return port(s) of a named k8s-service

---

common/defaults.go
common/operations.go

moved examples to common

---

common/operations.go

added smi and common operations

---

adapter/adapter.go
go.mod
go.sum
status/status.go

updated status and logger

---

adapter/adapter.go
adapter/configure.go
adapter/error.go
config/provider/viper.go
go.mod
go.sum

updated provider for kubeconfig support and updated kubernetes utilities

---

go.mod
go.sum
status/status.go

minor update for remote cloud persistence of smi

---

adapter/adapter.go
adapter/configure.go
go.mod
go.sum

added updated for meshery kube client

---

codecov.yml

Signed-off-by: aisuko <urakiny@gmail.com>

Add the codecov configuration

---

adapter/operations.go
go.mod
go.sum

Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

Add "Services" field in the Operation struct

---

go.mod
go.sum
status/status.go

fixes for updating resources

---

go.mod

fixes for update bug

---

README.md

Enhancing README docs.
No, I didn't because GH doesn't support it.

[Docs] README: linking to an excellent resource

---

adapter/configure.go

Signed-off-by: Michael Gfeller <mgfeller@mgfeller.net>
This PR fixes https://github.com/layer5io/meshery/issues/2603
Let's discuss this. If ok, a couple of test should be re-run (in-cluster, outside of cluster).

[Kubernetes] Cannot ping adapters when meshery deployed in Kubernetes

---

README.md

Signed-off-by: Ritvik Shukla <ritvikshukla261@gmail.com>
This PR fixes #54 

[README]:Added Community Forum

---

.github/ISSUE_TEMPLATE/documentation.md
.github/PULL_REQUEST_TEMPLATE.md
.github/config.yml

Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>
Changing the layer5 link to meshery link

Changing layer5 link to meshery link

---

go.mod
go.sum

Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>
This PR updates to meshkit v0.2.20

Update to meshkit v0.2.20

---

adapter/error.go
adapter/oam.go
go.mod
go.sum

Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>
This PR added runtime component generation

added runtime component generation

---

.github/label-commenter-config.yml
.github/workflows/label-commenter.yml

Signed-off-by: ruhi09 <rim.sen5613@gmail.com>
Added the workflow
This PR fixes #66 

[CI] Added the workflow

---

adapter/configure.go

Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>
This PR make auth info work with exec plugins.

validate kubeconfigs with exec based auth plugins

---

adapter/error.go

Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>
Improve error message returned when auth info are invalid

Improve error message returned when auth info are invalid

---

.github/workflows/newcomers-alert.yml

Signed-off-by: Ankita Pareek <ankitapareek2000@gmail.com>
- This PR adds a workflow to notify about good first issues on the #newcomer slack channel of Layer5.
- The slack.yaml file is already up-to-date.
This PR fixes #75 

Added newcomers-alert.yml to notify about good first issues on slack

---

.github/workflows/ci.yml
adapter/error.go
adapter/oam.go

Add support for component creation 

---

adapter/configure.go

Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

Add the name of k8s context for better logs

---

adapter/oam.go
go.mod
go.sum

Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

Use context in component generation

---

adapter/adapter.go

Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

Include kubeconfighandler

---

adapter/adapter.go
adapter/oam.go

Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>
The definition and schema files opened weren't being closed properly causing failed registration in some cases where the OS set limit of opened files is exceeded.

Fix skipped file closing

---

Makefile

Update Makefile to check the codebase
This PR fixes https://github.com/meshery/meshery-adapter-library/issues/5
If there are any suggestions to make changes, please let me know.

[chore] Update Makefile

---

adapter/oam.go
go.mod
go.sum

Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

Change Meshmodel with latest changes in database

---

adapter/oam.go

Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

Set all model names to lowercase

---

adapter/oam.go

Remove OAM

---

.github/workflows/ci.yml

Bump go version for CI

---

Makefile
adapter/adapter.go
adapter/error.go
adapter/logger.go
adapter/meshmodel.go
adapter/oam.go
adapter/operations.go
api/grpc/handlers.go
go.mod
go.sum

Reverts meshery/meshery-adapter-library#141
The code here is still referenced by the adapters and breaks the functionality.

Revert "Remove OAM related code"

---

go.mod
go.sum

bump meshkit to latest

---

adapter/error.go
adapter/logger.go
adapter/meshmodel.go
adapter/oam.go
adapter/register.go

This PR adds
1. Adapter `model` registration functions.
2. Removes/replaces traces of OAM with new `models`.

[models] Add adapter model registration funcs.

---

doc/design-specs/design-specs20230104.md
doc/design-specs/design-specs20230108.md
doc/design-specs/design-specs20230110.md
doc/design-specs/design-specs20230125.md
doc/design-specs/design-specs20230130.md
doc/design-specs/design-specs20230218.md
doc/design-specs/design-specs20230226.md
doc/design-specs/design-specs20230301.md
doc/design-specs/design-specs20230327.md
doc/design-specs/design-specs20230331.md
doc/design-specs/design-specs20230421.md
doc/design-specs/design-specs20230505.md
doc/design-specs/design-specs20230526.md
doc/design-specs/design-specs20230531.md
doc/design-specs/design-specs20230620.md
doc/design-specs/design-specs20230629.md
doc/design-specs/design-specs20230630.md
doc/design-specs/design-specs20230711.md
doc/design-specs/design-specs20230713.md
doc/design-specs/design-specs20230808.md
doc/design-specs/design-specs20230812.md
doc/design-specs/design-specs20231006.md
doc/design-specs/design-specs20231017.md
doc/design-specs/design-specs20231029.md
doc/design-specs/design-specs20231127.md
doc/design-specs/design-specs20231201.md

Historical action items... finally documented.
There's more from the archives, but here is for 2023.

design specs minutes
